[versions]
androidGradlePlugin = "9.0.1"
kotlin = "2.2.10"

[plugins]
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
