[versions]
androidGradlePlugin = "9.5.0-alpha05"
kotlin = "2.3.21"

[plugins]
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
