[versions]
androidGradlePlugin = "8.4.0-beta01"
kotlin = "1.9.20"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

